class TextConstant {
  static const Map ar = {
    "SplashScreen": {"SplashText": "WALLPAPER APP"},
    "WelcomeScreen": {
      "Heading": "Mapic",
      "Description":
          "تعرف على أفضل الأماكن والفعاليات الترفيهية بمدينة الرياض عبر التسجيل بالتطبيق",
      "SigninButton": "تسجيل الدخول",
      "NewUser": "مستخدم جديد",
    },
    "EditProfileScreen": {
      "ImageText": "تغیرہ الصورۃ",
      "name": "اللأسم",
      "Email": "البرید اللألکتروني",
      "Password": "الرقم السري",
      "Update": "تحدیث؟ ",
      "ButtonText": "حفظ التغییرات",
    },
    "SignInScreen": {
      "LoginText": "تسجیل الدخول",
      "UserName": "اسم المستخدم",
      "Password": "الرقم السري",
      "Login": "تسجيل دخول",
      "ForgotYourPassword": "نسیت کلمۃ المرور؟",
    },
    "ResetPassword": {
      "HeadingText": "إعادة ضبط الرقم السري",
      "EnterEmail": "أدخل بريدك الإلكتروني",
      "TextButtonField": "إلغاء العملية",
      "ButtonText": "إدخال",
      "CancelOperation": "إلغاء العملية",
    },
    "ChangePasswordScreen": {
      "ChangeThePassword": "تغيير الرقم السري",
      "CurrentPassword": "الرقم السري الحالي",
      "TheNewPassword": "الرقم السري الجديد",
      "ReEnter": "أعد إدخال الرقم السري الجديد",
      "SavingChanges": "حفظ التغييرات",
      "CancelOperation": "إلغاء العملية",
    },
    "CreateAccount": {
      "HeadingText": "إنشاء حساب",
      "Name": "اللأسم",
      "Email": "البرید اللألکتروني",
      "UserName": "اسم المستخدم",
      "Password": "الرقم السري",
      "ButtonText": "إنشاء",
    },
    "SearchScreen": {
      "AppBarText": "إبحث هنا",
      "Resturant": "مطاعم",
      "Gardens": "حدائق",
      "Cafes": "مقاهي",
      "Libraries": "مکاتبات",
      "Title": "العنوان",
      "WorkTime": "اوقات العمل",
      "Category": "التصنيف",
      "RecordYourVisit": "سجل زيارتك",
      "Comments": "التعليقات",
      "PlaceName": "اسم المكان",
      "Categories": "التصنيفات",
      "DropDownHint": "إكثر تصنيف",
      "DropDownList1": "المطاعم",
      "DropDownList2": "المقاهي",
      "DropDownList3": "حدائق",
      "DropDownList4": "مكتبات",
      "AddNewReview": "إضافة تقييم",
      "WriteAComment": "إكتب تعليق",
      "AddAPhoto": "إضافة صورة",
      "AddtoMap": "إضافة إلى الخريطة",
      "Cancellation": "إلغاء",
    },
    "AllowLocation": {
      "Permission": "السماح للتطبيق بالوصول إلى موقعك أثناء استخدامك للتطبيق",
      "Allow": "السماح",
      "DisAllow": "عدم السماح",
    },
    "InfoScreen": {
      "UserName": "اسم الیوزر",
      "One": "متابعین",
      "Two": "متابعون",
      "Three": "رقم",
      "Four": "رقم",
      "A-Map": "خريطة",
    },
    "Notification": {
      "Notification": "الإشعارات",
      "Friend": "صديق",
      "Jolt": "جولت",
      "RiyadhPark": "الرياض بارك",
    },
  };
}
